{
  "hash": "8208b572db6a0fd7bc1a2b36e3e06055",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Exam 1 Review\nsubtitle: Lecture 12\nauthor: Prof. Mine Çetinkaya-Rundel\ndate: 2026-09-30\nformat: \n  revealjs: \n    output-file: 12-exam-I-review-slides.html\n    footer: \"[🔗 sta199-f26.github.io](https://sta199-f26.github.io/)\"\n    theme: slides.scss\n    transition: fade\n    slide-number: true\n    logo: \"/slides/images/logo.png\"\n    toc: false\n  html: \n    code-link: true\nfilters:\n  - ../remove-fmt-skip.lua\n---\n\n\n\n\n\n\n\n# Warm-up\n\n## While you wait: Participate 📱💻 {.xsmall}\n\n- Check your email (and your spam folder) for an email from TEAMMATES\n\n- Fill out your peer evaluation for your team members\n\n::: caution-warning\nIf you fail to submit your feedback, you're not eligible to receive the points they give you.\n:::\n\n## From last time {.smaller}\n\n::: appex\n-   Go to your ae project in Positron.\n\n-   If you haven't yet done so, make sure all of your changes up to this point are committed and pushed, i.e., there's nothing left in your source control pane.\n\n-   If you haven't yet done so, pull to get today's application exercise file: `ae-07-chronicle-scrape-I.qmd`.\n\n-   Work through the application exercise in class, and render, commit, and push your edits by the end of class.\n:::\n\n# Exam 1 review\n\n## Exam 1 {.smaller}\n\nExam 1 is on Wednesday, starts promptly at 1:25 pm!\n\n- Covers all material up to and including today's lecture\n\n- Sample exam + model solutions for select HW questions are posted\n\n- Exam will be in class, closed book, no calculators, no computers, just 1 notes sheet\n\n- Notes sheet: 8.5x11, both sides, hand written or typed, any content you want, must be prepared by you\n\n- We'll direct you to your seat so get here early to allow time to get settled and read the instructions\n\n## Types of questions {.smaller}\n\n- Multiple-choice:\n  - Some will be single best answer, no partial credit\n  - Some will be *at least one* correct answer, with partial credit, and clearly identified with \"Select all that apply\"\n\n- Open-ended: \n  - Short answer, show your work, justify your reasoning\n  - With partial credit\n\n## Q1: Variable types {.xsmall}\n\n`blizzard_salary` has **409 rows and 4 columns**. Each row is a worker who completed the spreadsheet. Which statements are correct? **Select all that apply.**\n\na. The dataset has 399 rows.\nb. The dataset has 4 columns. [**Correct**]{.fragment}\nc. Each row represents a Blizzard Entertainment worker who filled out the spreadsheet. [**Correct**]{.fragment}\nd. `percent_incr` is numerical and discrete.\ne. `salary_type` is numerical.\nf. `annual_salary` is numerical. [**Correct**]{.fragment}\ng. `performance_rating` is categorical and ordinal. [**Correct**]{.fragment}\n\n## Q9: Where did the observations go? — question {.xsmall}\n\nA friend notices that the total number of observations in this plot seems lower than the total in `blizzard_salary` (**409 workers**). What might be going on here? Explain your reasoning.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](12-exam-I-review_files/figure-revealjs/q9-question-plot-1.png){fig-alt='Stacked counts of workers by salary type and performance rating; both bars together contain fewer than 409 workers.' width=100%}\n:::\n:::\n\n\n[**Observations with missing values for both variables won't be represented on the plot.**]{.fragment}\n\n## Q13: Reviewing an interpretation — question {.xsmall}\n\n\n\n::: columns\n\n::: {.column width=\"75%\"}\n\nFor **Top performers**, a team writes: “The relationship is positive, having a higher salary results in a higher percent increase. There is one clear outlier.” Which peer review notes are accurate and helpful? **Select all that apply.**\n\n:::\n\n::: {.column width=\"25%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](12-exam-I-review_files/figure-revealjs/q13-top-plot-1.png){fig-alt='Salary versus percent increase for Top performers, showing a positive roughly linear association with substantial scatter.' width=100%}\n:::\n:::\n\n\n:::\n\n:::\n\na. The interpretation is complete and perfect.\nb. It doesn't mention the direction.\nc. It doesn't mention the form, which is linear. [**Correct.**]{.fragment}\nd. It doesn't mention the strength, which is somewhat strong. [**Correct.**]{.fragment}\ne. There isn't a clear outlier; identify any potential outlier by its salary and/or percent increase. [**Correct.**]{.fragment}\nf. The interpretation is causal; observational data do not establish which variable causes the other or rule out other explanations. [**Correct.**]{.fragment}\n\n## Q16: Which bar plot? {.xsmall}\n\nWhich plot is produced by this code? [**Correct: D.**]{.fragment}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(penguins, aes(x = island, fill = species)) +\n  geom_bar()\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](12-exam-I-review_files/figure-revealjs/q16-options-1.png){fig-alt='Five options: A island proportions filled by species; B species proportions filled by island; C horizontal species proportions; D island counts filled by species; E horizontal species counts filled by island.' width=95%}\n:::\n:::\n\n\n## Q17: Reading a tibble {.xsmall}\n\nBased on this output, which statements **must be true**? **Select all that apply.**\n\n::: columns\n::: {.column width=\"60%\"}\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 336,776 × 19\n    year month   day arr_delay carrier dep_time sched_dep_time\n   <int> <int> <int>     <dbl> <chr>      <int>          <int>\n 1  2013     1     1        11 UA           517            515\n 2  2013     1     1        20 UA           533            529\n 3  2013     1     1        33 AA           542            540\n 4  2013     1     1       -18 B6           544            545\n 5  2013     1     1       -25 DL           554            600\n 6  2013     1     1        12 UA           554            558\n 7  2013     1     1        19 B6           555            600\n 8  2013     1     1       -14 EV           557            600\n 9  2013     1     1        -8 B6           557            600\n10  2013     1     1         8 AA           558            600\n# ℹ 336,766 more rows\n# ℹ 12 more variables: dep_delay <dbl>, arr_time <int>,\n#   sched_arr_time <int>, flight <int>, tailnum <chr>,\n#   origin <chr>, dest <chr>, air_time <dbl>, distance <dbl>,\n#   hour <dbl>, minute <dbl>, time_hour <dttm>\n```\n\n\n:::\n:::\n\n\n:::\n::: {.column width=\"40%\"}\n\na. `flights` is a tibble. [**Correct.**]{.fragment}\nb. `flights` has 10 rows.\nc. `flights` has 8 columns.\nd. `carrier` is a character variable. [**Correct.**]{.fragment}\ne. There are no missing data in `flights`.\n\n:::\n:::\n\n## Q27: Summing a condition {.xsmall}\n\nWhich statements about the code and its result are true? **Select all that apply.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmovies |>\n  summarize(sum(release_country == \"United States\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  `sum(release_country == \"United States\")`\n                                      <int>\n1                                       435\n```\n\n\n:::\n:::\n\n\na. It evaluates whether each `release_country` equals `\"United States\"`, resulting in logical values. [**Correct.**]{.fragment}\nb. It filters out rows where `release_country` is not `\"United States\"` and counts the remaining rows.\nc. It sums the logical values, treating each `TRUE` as 1 and each `FALSE` as 0. [**Correct.**]{.fragment}\nd. It results in a character vector.\ne. The result shows 435 movies released in the United States. [**Correct.**]{.fragment}\n\n## Q29: A 6 × 6 result {.xsmall}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmovies |>\n  count(rating, genre) |>\n  pivot_wider(names_from = genre, values_from = n, values_fill = 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  rating    Other Drama Action Comedy Horror\n  <fct>     <int> <int>  <int>  <int>  <int>\n1 G             5     1      1      1      0\n2 PG           38    13     10     18      0\n3 PG-13        19    25     35     35      0\n4 R            45    50     57     96     21\n5 NC-17         1     2      0      1      0\n6 Not Rated     4    11      4      6      1\n```\n\n\n:::\n:::\n\n\nWhich statements are true? **Select all that apply.**\n\na. The code counts movies in each rating and genre combination. [**Correct.**]{.fragment}\nb. The code sorts the results in descending order.\nc. Each row of the output is a movie.\nd. The output shows six distinct ratings in the dataset. [**Correct.**]{.fragment}\ne. The code reduces the number of variables and observations in the `movies` data frame to six.\n\n## Q31: Reshaping inflation data — question {.xsmall}\n\n`country_inflation` has **38 rows and 34 columns**: one row per country, a `country` column, and annual inflation columns for **1993–2025**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncountry_inflation_long <- country_inflation |>\n  pivot_longer(\n    cols = !country,\n    names_to = \"year\",\n    names_transform = as.numeric,\n    values_to = \"inflation_rate\"\n  )\n```\n:::\n\n\n::: question\nHow many rows and columns does the result have? **Show where each number comes from.** What does each row represent, what did `pivot_longer()` do, and what does `names_transform = as.numeric` accomplish?\n:::\n\n## Q31: Reshaping inflation data — answer {.xsmall}\n\n**Rows: 1,254. Columns: 3.** Each row represents **one country in one year**.\n\n1. **38** is the number of countries (the original rows).\n2. **34 − 1 = 33** columns are year columns: exclude the one `country` column. Equivalently, **2025 − 1993 + 1 = 33** years.\n3. Each country becomes **33 rows**, so the total is:\n\n$$38 \\times 33 = 38 \\times 30 + 38 \\times 3 = 1{,}140 + 114 = 1{,}254$$\n\nThe output columns are **`country` + `year` + `inflation_rate` = 3**:\n\n- `country` is retained and repeated for each year.\n- The 33 old column **names** become values in `year`.\n- Their cell **values** become values in `inflation_rate`.\n\nMissing inflation values still get rows; this code does not drop them.\n\n## Q32: Ratios and the top five — question {.xsmall}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncountry_inflation |>\n  filter(!is.na(`1993`), !is.na(`2025`)) |>\n  mutate(inf_ratio = `2025` / `1993`) |>\n  select(country, inf_ratio) |>\n  arrange(desc(inf_ratio)) |>\n  slice_head(n = 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n  country        inf_ratio\n  <chr>              <dbl>\n1 New Zealand         2.20\n2 Australia           1.64\n3 Denmark             1.51\n4 Ireland             1.50\n5 United Kingdom      1.48\n```\n\n\n:::\n:::\n\n\n**Part 1:** What does the resulting data frame represent? What does New Zealand's `inf_ratio` of 2.20 mean?\n\n**Part 2:** What would change if the `filter()` step were removed? Why could that be misleading?\n\n## Q32: Ratios and the top five — answer {.xsmall}\n\n**Part 1:** These are the **five countries with the largest 2025-to-1993 inflation ratios**, in descending order.\n\n- A ratio of **2.20** means New Zealand's 2025 inflation rate was **2.20 times its 1993 rate** (120% higher). It does not mean the 2025 inflation rate was 2.20%.\n- `arrange(desc(inf_ratio))` puts the largest ratios first. **`slice_head(n = 5)` keeps the first five rows in that order.**\n\n**Part 2:** Without `filter()`, six countries would have `NA` ratios because at least one of their two rates is missing.\n\n- `arrange()` puts these `NA`s last. **For these data, the same five countries would still be returned.**\n- The top-five table cannot reveal whether an absent country has a smaller ratio or lacks data. Filtering makes the exclusion explicit; report that the ranking uses **32 of 38 countries**.\n\n## Q32: What exactly does `slice_head()` do? {.xsmall}\n\n**It selects rows by their current positions. It does not sort or calculate a summary.**\n\n| Stage | Rows | What happened? |\n|:--|--:|:--|\n| Start | 38 | One row per country |\n| `filter(...)` | 32 | Keep countries with both endpoint rates |\n| `mutate(...)` | 32 | Add one ratio to each row |\n| `select(...)` | 32 | Keep two columns |\n| `arrange(desc(inf_ratio))` | 32 | Put largest ratios first |\n| `slice_head(n = 5)` | 5 | Keep rows 1–5 |\n\nRemoving **only `slice_head(n = 5)`** keeps all **32 eligible countries**. It does not restore the six countries excluded by `filter()`.\n\n## Other questions {.smaller}\n\n- [Q2](/exam-review/exam-1-review.qmd#question-2)\n- [Q4](/exam-review/exam-1-review.qmd#question-4)\n- [Q7](/exam-review/exam-1-review.qmd#questions-6-and-7)\n- [Q8](/exam-review/exam-1-review.qmd#questions-8---10)\n- [Q14](/exam-review/exam-1-review.qmd#question-14)\n- [Q23](/exam-review/exam-1-review.qmd#question-23)\n- [Q24](/exam-review/exam-1-review.qmd#question-24)\n- [Q28](/exam-review/exam-1-review.qmd#question-28)\n- [Q30](/exam-review/exam-1-review.qmd#question-30)\n\n[Exam review answers](/exam-review/exam-1-review-A.qmd)\n",
    "supporting": [
      "12-exam-I-review_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}