---
title: "Improvement and progress I: from proposal to project"
subtitle: "Milestone 3"
categories: "Project"
execute:
  echo: false
---

::: callout-important
You must attend this lab in person and participate in the teamwork in person to be eligible for the points for this milestone.
Team members who are not in lab in person for this milestone will not be eligible for these points, regardless of their contribution throughout the rest of the project.
:::

By this point you've received feedback on your proposal and you should be working on incorporating that feedback to improve your project and making further progress on it.
This milestone ensures you're keeping on task and doing these things.

# Goals

The goals of this milestone are as follows:

-   Create a data dictionary
-   Incorporate feedback from your proposal
-   Make progress on your project prior to the peer review

::: callout-note
Moving forward, focus your work on `index.qmd` and other files within your repo as needed. Since the proposal has been completed and graded, you should not make further edits to `proposal.qmd`. If you encounter issues related to datasets you are no longer considering, simply close those issues rather than addressing them, and leave an appropriate comment.
:::

# Instructions

Make some progress, evidenced by commits to your repo since project milestone 2. 
These commits should

-   create a data dictionary for your chosen dataset
-   explicitly close issues opened as proposal feedback, and
-   make further progress on the project.

## Data dictionary

Add a data dictionary to the `README.md` file in the `data` folder describing each variable in your chosen dataset.

# Grading

This milestone will be graded for completion, not accuracy.
We will check to see if the team has made commits to their repo since project milestone 2 and closed all issues that were opened as part of proposal feedback.

-   0 points: No commits since project milestone 2

-   1 point: Only a single commit since project milestone 2, regardless of how many issues closed

-   2-4 points: More than 1 commit since project milestone 2 and but not all issues closed

-   5 points: More than 1 commit since project milestone 2, all issues closed, and a data dictionary for the chosen dataset is included (at least partially completed) in `data/README.md`
