---
title: "Improvement and progress II: polishing the project"
subtitle: Milestone 5
categories: Project
execute:
  echo: false
draft: false  
---

::: callout-important
You must attend this lab in person and participate in the teamwork in person to be eligible for all of the points for this milestone.
Team members who are not in the lab in person for this milestone will not be eligible for some of these points, regardless of their contribution throughout the rest of the project.
:::

By this point, you've received peer feedback on your project and should be incorporating that feedback and making further progress on your project.
This milestone helps you stay on track with that work.

# Goals

The goals of this milestone are as follows:

-   Incorporate feedback from your peers
-   Polish your project prior to your presentation and final write-up

# Instructions

Make some progress, evidenced by commits to your repo since project milestone 4. 
These commits should

-   explicitly close issues opened as peer feedback, and
-   make further progress on the project.

# Grading

| Total                   | 10 pts |
|-------------------------|--------|
| One or more commits since Milestone 4         | 2      |
| All issues closed       | 3      |
| Present in lab          | 5      |
