---
title: "Write-up"
subtitle: "Milestone 7"
categories: "Project"
---

# Write-up

## Expectations

Your written report must be completed in the `index.qmd` file and must be reproducible.
All team members should contribute to the GitHub repository, with regular meaningful commits.

Before you finalize your write up, make sure the printing of code chunks is off with the option `echo: false` in the YAML.

The mandatory components of the report are below.
You are free to add additional sections as necessary.
The report, including visualizations, should be no more than 10 pages long (if it were to be printed)**.** There is no minimum page requirement; however, you should comprehensively address all of the analysis in your report.

To check how many pages your report is, open it in your browser and go to File \> Print \> Save as PDF and review the number of pages.

Be selective in what you include in your final write-up.
The goal is to write a cohesive narrative that demonstrates a thorough and comprehensive analysis rather than explain every step of the analysis.

You are welcome to include an appendix with additional work at the end of the written report document; however, grading will largely be based on the content in the main body of the report.
You should assume the reader will ***not*** see the material in the appendix unless prompted to view it in the main body of the report.
The appendix should be neatly formatted and easy for the reader to navigate.
It is not included in the 10-page limit.

## Components

### Introduction

This section includes an introduction to the project motivation and research question.

**Grading criteria:** The research question and motivation are clearly stated in the introduction, including citations for the data source and any external research.

### Data

This section includes a description of the data.
Describe the data and definitions of key variables.
Also include a description of any data cleaning steps you took to prepare the data for analysis.

**Grading criteria:** The data are clearly described, including a description about how the data were originally collected and a concise definition of the variables relevant to understanding the report.
The data cleaning process is clearly described, including any decisions made in the process (e.g., creating new variables, removing observations, etc.) The exploratory data analysis helps the reader better understand the observations in the data along with interesting and relevant relationships between the variables.

### Analysis

This is where you will discuss your findings and describe the key results from your analysis.
The goal is not to interpret every single element of a visualization or output shown, but instead to address the research questions, using the interpretations to support your conclusions.
Focus on the variables that help you answer the research question and that provide relevant context for the reader.


**Grading criteria:** The analysis steps are appropriate for the data and research question.
A thorough and careful approach is used to determine analysis types and any concerns over appropriateness of analyses chosen are addressed.
The analysis results are clearly assesses and interesting findings from the analysis are described.
Interpretations are used to to support the key findings and conclusions, rather than merely listing, e.g., the interpretation of every summary statistic.

### Discussion

In this section you'll include a summary of what you have learned about your research question along with statistical arguments supporting your conclusions.
In addition, discuss the limitations of your analysis and provide suggestions on ways the analysis could be improved.
Any potential issues pertaining to the reliability and validity of your data and appropriateness of the statistical analysis should also be discussed here.
Lastly, you might choose to include ideas for future work, but do this only if you have realistic ideas that are relevant to your project.

**Grading criteria:** Overall conclusions from analysis are clearly described, and the analysis results are put into the larger context of the subject matter and original research question.
There is thoughtful consideration of potential limitations of the data and/or analysis.
If ideas for future work are described, these are realistic and relevant to the project.

### Organization + formatting

This is an assessment of the overall presentation and formatting of the written report.

**Grading criteria:** The report neatly written and organized with clear section headers and appropriately sized figures with informative labels.
Numerical results are displayed with a reasonable number of digits, and all visualizations are neatly formatted.
All citations and links are properly formatted.
If there is an appendix, it is reasonably organized and easy for the reader to find relevant information.
All code, warnings, and messages are suppressed.
The main body of the written report (not including the appendix) is no longer than 10 pages.

### Code style + smell

This is an assessment of the overall presentation and formatting of the written report.

**Grading criteria:** The report neatly written and organized with clear section headers and appropriately sized figures with informative labels.
Numerical results are displayed with a reasonable number of digits, and all visualizations are neatly formatted.
All citations and links are properly formatted.
If there is an appendix, it is reasonably organized and easy for the reader to find relevant information.
All code, warnings, and messages are suppressed.
The main body of the written report (not including the appendix) is no longer than 10 pages.

## Grading

The write-up is due on Thursday, November 13 at 11:59 pm. 

It is worth 30 points, broken down as follows:

| Total                         | 30 pts |
|-------------------------------|--------|
| **Introduction**              |  2 pts |
| **Data**                      |  3 pts |
| **Analysis**                  | 15 pts |
| **Discussion**                |  3 pts |
| **Organization + formatting** |  2 pts |
| **Code style + smell**        |  5 pts |
