{
  "hash": "576bc8ec620187824f330b07d6192387",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Exploratory data analysis I\"\nsubtitle: \"Lecture 4\"\ndate: \"2026-09-02\"\nformat: \n  revealjs: \n    output-file: 05-exploratory-data-analysis-I-slides.html\n    footer: \"[🔗 sta199-f26.github.io](https://sta199-f26.github.io/)\"\n    theme: slides.scss\n    transition: fade\n    slide-number: true\n    logo: \"slides/images/logo.png\" \n    toc: false\n  html: \n    code-link: true\n---\n\n\n\n# Warm up\n\n## While you wait: Participate 📱 {.smaller}\n\n::: {.columns}\n\n::: {.column width=\"70%\"}\n\n::: wooclap\nSuppose you have a dataset `df` with 100 rows and 5 columns: `x1`, `x2`, `x3`, `x4`, and `x5`. `x1` is a categorical variable with levels `a` and `b`. You run the following code:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx |>\n  filter(x1 == \"a\") |>\n  select(x1, x2, x5)\n```\n:::\n\n\nThe resulting data frame will have:\n\n::: wooclap-choices\n- 3 columns, 50 rows \n- 3 columns, 100 rows\n- 3 columns, can't tell how many rows\n- 5 columns, 100 rows\n- 5 columns, can't tell how many rows\n:::\n\n:::\n\n:::\n\n::: {.column width=\"30%\"}\n\n![](images/05/wooclap-qr.png){width=\"200\" fig-align=\"center\" fig-alt=\"QR code for Wooclap\"}\n\nGo to [wooclap.com](https://app.wooclap.com/KUCTINK) and use the code KUCTINK.\n\n:::\n\n::: \n\n## Announcements\n\nHW 1 is due tonight at 11:59 pm:\n\n- Push all work to GitHub.\n\n- Submit a PDF of your PDF file to Gradescope and mark your pages.\n\n## *Getting to know you* feedback: Questions {.smaller}\n\n::: incremental\n- Is the course designed for students with no prior coding or statistics background?\n- What is the balance between learning statistical concepts and programming in R? How often will students code?\n- How should students use readings, videos, and other materials—and which are essential?\n- What should students expect from discussion projects, collaboration, and required uploads?\n- What will exams look like, and what practice or study materials will be available?\n- Where can students get help, and what kinds of collaboration are appropriate?\n- How does the course compare to COMPSCI 216 (Everything Data) and STA 323 (Statistical Computing)?\n:::\n\n## *Getting to know you* feedback: Concerns {.smaller}\n\n::: incremental\n- Dominant concern: lack of prior coding experience—especially learning R, syntax, troubleshooting, and technical tools such as Git and GitHub\n- Keeping pace: falling behind or being less prepared than classmates\n- Workload: time management for labs, HW, projects, and other commitments\n- Assessment: format of exams, details of grading, and effective study strategies\n- Smaller themes: Group-project dynamics, large-lecture setting, and confidence with math/statistical terminology\n:::\n\n# From last time\n\n## In this class, you will... {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\nBuild cakes (`ggplot`) ![](images/05/cake.png)\n:::\n\n::: {.column width=\"50%\"}\nStack dolls (pipe `|>`) ![](images/05/matryoshka.png)\n:::\n:::\n\nMaster these constructs, and everything will be A-Ok!\n\n::: aside\nSource: [Cake by Anirban Sengupta on Unsplash](https://unsplash.com/photos/white-pink-and-yellow-cake-GQvNc4bDRYw) and [Matryoshka dolls by Julia Kadel  on Unsplash](https://unsplash.com/photos/a-group-of-russian-nesting-dolls-sitting-on-a-table-YmULswIbc3I).\n:::\n\n# Exploratory data analysis\n\n## Packages\n\n- For data wrangling and visualization: [**tidyverse**](https://www.tidyverse.org/packages/)\n- For pretty axis labels: [**scales**](https://scales.r-lib.org)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(scales)\n```\n:::\n\n\n## Data: `gerrymander`\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngerrymander <- read_csv(\"data/gerrymander.csv\")\n```\n:::\n\n\n## What is gerrymandering?\n\n<https://www.washingtonpost.com/business/wonkblog/gerrymandering-explained/2016/04/21/e447f5c2-07fe-11e6-bfed-ef65dff5970d_video.html>\n\n## Participate 📱💻 \n\n::: {.columns}\n\n::: {.column width=\"75%\"}\n\n::: wooclap\n\nYou are given a new dataset to analyze. What are some of the first things you would do to get to know the data?\n\n:::\n\n:::\n\n::: {.column width=\"25%\"}\n\n![](images/05/wooclap-qr.png){width=\"200\" fig-align=\"center\" fig-alt=\"QR code for Wooclap\"}\n\nGo to [wooclap.com](https://app.wooclap.com/KUCTINK) and use the code KUCTINK.\n\n:::\n\n::: \n\n## Data: `gerrymander` {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(gerrymander)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 443\nColumns: 14\n$ district       <chr> \"AK-00\", \"AL-01\", \"AL-02\", \"AL-03\", \"AL-04\", \"AL-05\", \"…\n$ state_abb      <chr> \"AK\", \"AL\", \"AL\", \"AL\", \"AL\", \"AL\", \"AL\", \"AL\", \"AR\", \"…\n$ state          <chr> \"Alaska\", \"Alabama\", \"Alabama\", \"Alabama\", \"Alabama\", \"…\n$ house_rep_20   <chr> \"Don Young\", \"Jerry Carl\", \"Barry Moore\", \"Mike Rogers\"…\n$ house_party_20 <chr> \"Republican\", \"Republican\", \"Republican\", \"Republican\",…\n$ house_rep_22   <chr> \"Mary Sattler Peltola\", \"Jerry L Carl\", \"Barry Moore\", …\n$ house_party_22 <chr> \"Democrat\", \"Republican\", \"Republican\", \"Republican\", \"…\n$ house_rep_24   <chr> \"Nick Begich\", \"Barry Moore\", \"Shomari Figures\", \"Mike …\n$ house_party_24 <chr> \"Republican\", \"Republican\", \"Democrat\", \"Republican\", \"…\n$ harris_24      <dbl> 41.41, 21.89, 53.52, 26.18, 15.96, 34.20, 29.68, 61.45,…\n$ trump_24       <dbl> 54.54, 76.94, 45.31, 72.71, 83.02, 64.02, 68.47, 37.50,…\n$ gerry_22       <chr> NA, \"F\", \"F\", \"F\", \"F\", \"F\", \"F\", \"F\", \"C\", \"C\", \"C\", \"…\n$ gerry_24       <chr> NA, \"B\", \"B\", \"B\", \"B\", \"B\", \"B\", \"B\", \"C\", \"C\", \"C\", \"…\n$ gerry_26       <chr> NA, \"B\", \"B\", \"B\", \"B\", \"B\", \"B\", \"B\", \"C\", \"C\", \"C\", \"…\n```\n\n\n:::\n:::\n\n\n. . .\n\n::: question\nHow many congressional districts are there in the United States? How many rows are there in the data? Do the number of rows in the data match your expectations?\n:::\n\n## Data: `gerrymander` {.smaller}\n\n-   Rows: Congressional districts in the 2020, 2022, and 2024 elections\n\n-   Columns:\n\n    -   Congressional district, state abbreviation, and state name\n\n    -   Name and party of the House candidate who won in 2020, 2022, and 2024\n\n    -   2024 election: % for Harris, % for Trump\n\n    -   Gerrymandering score for 2022, 2024, and 2026 (A: Good, B: Better than average with some bias, C: Average, D/F: Poor)\n\n## Variable types: `district`  {.smaller}\n\n::: columns\n\n::: {.column .xsmall}\n\n| Variable         | Type                               |\n|------------------|------------------------------------|\n| `district`       | [categorical, ID]{.fragment}       |\n| `state_abb`      |                                    |\n| `state`          |                                    |\n| `house_rep_20`   |                                    |\n| `house_party_20` |                                    |\n| `house_rep_22`   |                                    |\n| `house_party_22` |                                    |\n| `house_rep_24`   |                                    |\n| `house_party_24` |                                    |\n| `harris_24`      |                                    |\n| `trump_24`       |                                    |\n| `gerry_22`       |                                    |\n| `gerry_24`       |                                    |\n| `gerry_26`       |                                    |\n\n:::\n\n::: {.column .small}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngerrymander |>\n  select(district)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 443 × 1\n   district\n   <chr>   \n 1 AK-00   \n 2 AL-01   \n 3 AL-02   \n 4 AL-03   \n 5 AL-04   \n 6 AL-05   \n 7 AL-06   \n 8 AL-07   \n 9 AR-01   \n10 AR-02   \n# ℹ 433 more rows\n```\n\n\n:::\n:::\n\n\n:::\n:::\n\n## Variable types: `state_abb`  {.smaller}\n\n::: columns\n\n::: {.column .xsmall}\n\n| Variable         | Type                               |\n|------------------|------------------------------------|\n| `district`       | categorical, ID                    |\n| `state_abb`      | [categorical]{.fragment}           |\n| `state`          |                                    |\n| `house_rep_20`   |                                    |\n| `house_party_20` |                                    |\n| `house_rep_22`   |                                    |\n| `house_party_22` |                                    |\n| `house_rep_24`   |                                    |\n| `house_party_24` |                                    |\n| `harris_24`      |                                    |\n| `trump_24`       |                                    |\n| `gerry_22`       |                                    |\n| `gerry_24`       |                                    |\n| `gerry_26`       |                                    |\n\n:::\n\n::: {.column .small}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngerrymander |>\n  select(district, state_abb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 443 × 2\n   district state_abb\n   <chr>    <chr>    \n 1 AK-00    AK       \n 2 AL-01    AL       \n 3 AL-02    AL       \n 4 AL-03    AL       \n 5 AL-04    AL       \n 6 AL-05    AL       \n 7 AL-06    AL       \n 8 AL-07    AL       \n 9 AR-01    AR       \n10 AR-02    AR       \n# ℹ 433 more rows\n```\n\n\n:::\n:::\n\n\n:::\n:::\n\n## Variable types: `state`  {.smaller}\n\n::: columns\n\n::: {.column .xsmall}\n\n| Variable         | Type                               |\n|------------------|------------------------------------|\n| `district`       | categorical, ID                    |\n| `state_abb`      | categorical                        |\n| `state`          | [categorical]{.fragment}           |\n| `house_rep_20`   |                                    |\n| `house_party_20` |                                    |\n| `house_rep_22`   |                                    |\n| `house_party_22` |                                    |\n| `house_rep_24`   |                                    |\n| `house_party_24` |                                    |\n| `harris_24`      |                                    |\n| `trump_24`       |                                    |\n| `gerry_22`       |                                    |\n| `gerry_24`       |                                    |\n| `gerry_26`       |                                    |\n\n:::\n\n::: {.column .small}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngerrymander |>\n  select(district, state)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 443 × 2\n   district state   \n   <chr>    <chr>   \n 1 AK-00    Alaska  \n 2 AL-01    Alabama \n 3 AL-02    Alabama \n 4 AL-03    Alabama \n 5 AL-04    Alabama \n 6 AL-05    Alabama \n 7 AL-06    Alabama \n 8 AL-07    Alabama \n 9 AR-01    Arkansas\n10 AR-02    Arkansas\n# ℹ 433 more rows\n```\n\n\n:::\n:::\n\n\n:::\n:::\n\n## Variable types: House representatives  {.smaller}\n\n::: columns\n\n::: {.column .xsmall width=\"30%\"}\n\n| Variable         | Type                               |\n|------------------|------------------------------------|\n| `district`       | categorical, ID                    |\n| `state_abb`      | categorical                        |\n| `state`          | categorical                        |\n| `house_rep_20`   | [categorical, ID]{.fragment fragment-index=\"1\"}       |\n| `house_party_20` |                                    |\n| `house_rep_22`   | [categorical, ID]{.fragment fragment-index=\"1\"}       |\n| `house_party_22` |                                    |\n| `house_rep_24`   | [categorical, ID]{.fragment fragment-index=\"1\"}       |\n| `house_party_24` |                                    |\n| `harris_24`      |                                    |\n| `trump_24`       |                                    |\n| `gerry_22`       |                                    |\n| `gerry_24`       |                                    |\n| `gerry_26`       |                                    |\n\n:::\n\n::: {.column .small width=\"70%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngerrymander |>\n  select(district, starts_with(\"house_rep\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 443 × 4\n   district house_rep_20                   house_rep_22             house_rep_24\n   <chr>    <chr>                          <chr>                    <chr>       \n 1 AK-00    \"Don Young\"                    \"Mary Sattler Peltola\"   \"Nick Begic…\n 2 AL-01    \"Jerry Carl\"                   \"Jerry L Carl\"           \"Barry Moor…\n 3 AL-02    \"Barry Moore\"                  \"Barry Moore\"            \"Shomari Fi…\n 4 AL-03    \"Mike Rogers\"                  \"Mike Rogers\"            \"Mike Roger…\n 5 AL-04    \"Robert B Aderholt\"            \"Robert B Aderholt\"      \"Robert B. …\n 6 AL-05    \"Mo Brooks\"                    \"Dale Strong\"            \"Dale W. St…\n 7 AL-06    \"Gary J Palmer\"                \"Gary J Palmer\"          \"Gary J. Pa…\n 8 AL-07    \"Terri A Sewell\"               \"Terri A Sewell\"         \"Terri A. S…\n 9 AR-01    \"Eric A \\\\\\\"Rick\\\\\\\" Crawford\" \"Eric A Â\\u0080\\u009cRi… \"Eric A. \\\\…\n10 AR-02    \"J French Hill\"                \"J French Hill\"          \"J. French …\n# ℹ 433 more rows\n```\n\n\n:::\n:::\n\n\n:::\n:::\n\n## Variable types: winning parties  {.smaller}\n\n::: columns\n\n::: {.column .xsmall}\n\n| Variable         | Type                               |\n|------------------|------------------------------------|\n| `district`       | categorical, ID                    |\n| `state_abb`      | categorical                        |\n| `state`          | categorical                        |\n| `house_rep_20`   | categorical, ID                    |\n| `house_party_20` | [categorical]{.fragment fragment-index=\"1\"}           |\n| `house_rep_22`   | categorical, ID                    |\n| `house_party_22` | [categorical]{.fragment fragment-index=\"1\"}           |\n| `house_rep_24`   | categorical, ID                    |\n| `house_party_24` | [categorical]{.fragment fragment-index=\"1\"}           |\n| `harris_24`      |                                    |\n| `trump_24`       |                                    |\n| `gerry_22`       |                                    |\n| `gerry_24`       |                                    |\n| `gerry_26`       |                                    |\n\n:::\n\n::: {.column .small}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngerrymander |>\n  select(district, starts_with(\"house_party\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 443 × 4\n   district house_party_20 house_party_22 house_party_24\n   <chr>    <chr>          <chr>          <chr>         \n 1 AK-00    Republican     Democrat       Republican    \n 2 AL-01    Republican     Republican     Republican    \n 3 AL-02    Republican     Republican     Democrat      \n 4 AL-03    Republican     Republican     Republican    \n 5 AL-04    Republican     Republican     Republican    \n 6 AL-05    Republican     Republican     Republican    \n 7 AL-06    Republican     Republican     Republican    \n 8 AL-07    Democrat       Democrat       Democrat      \n 9 AR-01    Republican     Republican     Republican    \n10 AR-02    Republican     Republican     Republican    \n# ℹ 433 more rows\n```\n\n\n:::\n:::\n\n\n:::\n:::\n\n## Variable types: `harris_24` and `trump_24`  {.smaller}\n\n::: columns\n\n::: {.column .xsmall}\n\n| Variable         | Type                               |\n|------------------|------------------------------------|\n| `district`       | categorical, ID                    |\n| `state_abb`      | categorical                        |\n| `state`          | categorical                        |\n| `house_rep_20`   | categorical, ID                    |\n| `house_party_20` | categorical                        |\n| `house_rep_22`   | categorical, ID                    |\n| `house_party_22` | categorical                        |\n| `house_rep_24`   | categorical, ID                    |\n| `house_party_24` | categorical                        |\n| `harris_24`      | [numerical, continuous]{.fragment fragment-index=\"1\"} |\n| `trump_24`       | [numerical, continuous]{.fragment fragment-index=\"1\"} |\n| `gerry_22`       |                                    |\n| `gerry_24`       |                                    |\n| `gerry_26`       |                                    |\n\n:::\n\n::: {.column .small}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngerrymander |>\n  select(district, harris_24, trump_24)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 443 × 3\n   district harris_24 trump_24\n   <chr>        <dbl>    <dbl>\n 1 AK-00         41.4     54.5\n 2 AL-01         21.9     76.9\n 3 AL-02         53.5     45.3\n 4 AL-03         26.2     72.7\n 5 AL-04         16.0     83.0\n 6 AL-05         34.2     64.0\n 7 AL-06         29.7     68.5\n 8 AL-07         61.4     37.5\n 9 AR-01         26.4     71.7\n10 AR-02         41.0     56.6\n# ℹ 433 more rows\n```\n\n\n:::\n:::\n\n\n:::\n:::\n\n## Variable types: Gerrymandering level {.smaller}\n\n::: columns\n\n::: {.column .xsmall}\n\n| Variable         | Type                               |\n|------------------|------------------------------------|\n| `district`       | categorical, ID                    |\n| `state_abb`      | categorical                        |\n| `state`          | categorical                        |\n| `house_rep_20`   | categorical, ID                    |\n| `house_party_20` | categorical                        |\n| `house_rep_22`   | categorical, ID                    |\n| `house_party_22` | categorical                        |\n| `house_rep_24`   | categorical, ID                    |\n| `house_party_24` | categorical                        |\n| `harris_24`      | numerical, continuous              |\n| `trump_24`       | numerical, continuous              |\n| `gerry_22`       | [categorical, ordinal]{.fragment fragment-index=\"1\"}  |\n| `gerry_24`       | [categorical, ordinal]{.fragment fragment-index=\"1\"}  |\n| `gerry_26`       | [categorical, ordinal]{.fragment fragment-index=\"1\"}  |\n\n:::\n\n::: {.column .small}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngerrymander |>\n  select(district, starts_with(\"gerry\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 443 × 4\n   district gerry_22 gerry_24 gerry_26\n   <chr>    <chr>    <chr>    <chr>   \n 1 AK-00    <NA>     <NA>     <NA>    \n 2 AL-01    F        B        B       \n 3 AL-02    F        B        B       \n 4 AL-03    F        B        B       \n 5 AL-04    F        B        B       \n 6 AL-05    F        B        B       \n 7 AL-06    F        B        B       \n 8 AL-07    F        B        B       \n 9 AR-01    C        C        C       \n10 AR-02    C        C        C       \n# ℹ 433 more rows\n```\n\n\n:::\n:::\n\n\n:::\n:::\n\nBased on the [Gerrymandering Project's](https://nervous-noyce-f2ebc6.netlify.app/redistricting-report-card/) Redistricting Report Card. \n(A: Good, B: Better than average with some bias, C: Average, D/F: Poor)\n\n# Univariate analysis\n\n## Univariate analysis\n\nAnalyzing a single variable:\n\n::: incremental\n-   Numerical: histogram, box plot, density plot, etc.\n\n-   Categorical: bar plot, pie chart, etc.\n:::\n\n## Focus: 2024 Elections\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngerrymander_24 <- gerrymander |>\n  filter(!is.na(house_rep_24))\n\ndim(gerrymander_24)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 435  14\n```\n\n\n:::\n:::\n\n\n## Histogram - Step 1\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gerrymander_24)\n```\n\n::: {.cell-output-display}\n![](05-exploratory-data-analysis-I_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n## Histogram - Step 2\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gerrymander_24, aes(x = trump_24))\n```\n\n::: {.cell-output-display}\n![](05-exploratory-data-analysis-I_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n## Histogram - Step 3\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"2\"}\nggplot(gerrymander_24, aes(x = trump_24)) +\n  geom_histogram()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](05-exploratory-data-analysis-I_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n## Participate 📱💻 {.smaller}\n\n::: {.columns}\n\n::: {.column width=\"80%\"}\n\n::: {.wooclap .small}\nWhich of the following has the most appropriate binwidth for visualizing the distribution of `trump_24`?\n\n\n::: {.cell layout-ncol=\"2\"}\n::: {.cell-output-display}\n![](05-exploratory-data-analysis-I_files/figure-html/unnamed-chunk-17-1.png){width=480}\n:::\n\n::: {.cell-output-display}\n![](05-exploratory-data-analysis-I_files/figure-html/unnamed-chunk-17-2.png){width=480}\n:::\n\n::: {.cell-output-display}\n![](05-exploratory-data-analysis-I_files/figure-html/unnamed-chunk-17-3.png){width=480}\n:::\n\n::: {.cell-output-display}\n![](05-exploratory-data-analysis-I_files/figure-html/unnamed-chunk-17-4.png){width=480}\n:::\n:::\n\n\n:::\n\n:::\n\n::: {.column width=\"20%\"}\n\n![](images/05/wooclap-qr.png){width=\"200\" fig-align=\"center\" fig-alt=\"QR code for Wooclap\"}\n\nGo to [wooclap.com](https://app.wooclap.com/KUCTINK) and use the code KUCTINK.\n\n:::\n\n::: \n\n## Histogram - Step 4\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"3\"}\nggplot(gerrymander_24, aes(x = trump_24)) +\n  geom_histogram(binwidth = 5) +\n  scale_x_continuous(labels = label_percent(scale = 1))\n```\n\n::: {.cell-output-display}\n![](05-exploratory-data-analysis-I_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n## Histogram - Step 5 {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"4-9\"}\nggplot(gerrymander_24, aes(x = trump_24)) +\n  geom_histogram(binwidth = 5) +\n  scale_x_continuous(labels = label_percent(scale = 1)) +\n  labs(\n    title = \"Percent of vote received by Trump in 2024 Presidential Election\",\n    subtitle = \"From each Congressional District\",\n    x = \"Percent of vote\",\n    y = \"Count\"\n  )\n```\n\n::: {.cell-output-display}\n![](05-exploratory-data-analysis-I_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n## Box plot - Step 1\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gerrymander_24)\n```\n\n::: {.cell-output-display}\n![](05-exploratory-data-analysis-I_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n## Box plot - Step 2\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gerrymander_24, aes(x = trump_24))\n```\n\n::: {.cell-output-display}\n![](05-exploratory-data-analysis-I_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\n## Box plot - Step 3\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"2\"}\nggplot(gerrymander_24, aes(x = trump_24)) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](05-exploratory-data-analysis-I_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n## Box plot - Alternative Step 2 + 3\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gerrymander_24, aes(y = trump_24)) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](05-exploratory-data-analysis-I_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n## Box plot - Step 4 {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"3-8\"}\nggplot(gerrymander_24, aes(x = trump_24)) +\n  geom_boxplot() +\n  labs(\n    title = \"Percent of vote received by Trump in 2024 Presidential Election\",\n    subtitle = \"From each Congressional District\",\n    x = \"Percent of vote\",\n    y = NULL\n  )\n```\n\n::: {.cell-output-display}\n![](05-exploratory-data-analysis-I_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n## Density plot - Step 1\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gerrymander_24)\n```\n\n::: {.cell-output-display}\n![](05-exploratory-data-analysis-I_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\n## Density plot - Step 2\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gerrymander_24, aes(x = trump_24))\n```\n\n::: {.cell-output-display}\n![](05-exploratory-data-analysis-I_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\n## Density plot - Step 3\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"2\"}\nggplot(gerrymander_24, aes(x = trump_24)) +\n  geom_density()\n```\n\n::: {.cell-output-display}\n![](05-exploratory-data-analysis-I_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\n## Density plot - Step 4\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gerrymander_24, aes(x = trump_24)) +\n  geom_density(color = \"firebrick\")\n```\n\n::: {.cell-output-display}\n![](05-exploratory-data-analysis-I_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\n## Density plot - Step 5\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gerrymander_24, aes(x = trump_24)) +\n  geom_density(color = \"firebrick\", fill = \"firebrick1\")\n```\n\n::: {.cell-output-display}\n![](05-exploratory-data-analysis-I_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\n## Density plot - Step 6\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gerrymander_24, aes(x = trump_24)) +\n  geom_density(color = \"firebrick\", fill = \"firebrick1\", alpha = 0.5)\n```\n\n::: {.cell-output-display}\n![](05-exploratory-data-analysis-I_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\n## Density plot - Step 7\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gerrymander_24, aes(x = trump_24)) +\n  geom_density(\n    color = \"firebrick\",\n    fill = \"firebrick1\",\n    alpha = 0.5,\n    linewidth = 1\n  )\n```\n\n::: {.cell-output-display}\n![](05-exploratory-data-analysis-I_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\n## Density plot - Step 8 {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"3-8\"}\nggplot(gerrymander_24, aes(x = trump_24)) +\n  geom_density(\n    color = \"firebrick\",\n    fill = \"firebrick1\",\n    alpha = 0.5,\n    linewidth = 2\n  ) +\n  labs(\n    title = \"Percent of vote received by Trump in 2024 Presidential Election\",\n    subtitle = \"From each Congressional District\",\n    x = \"Percent of vote\",\n    y = \"Density\"\n  )\n```\n\n::: {.cell-output-display}\n![](05-exploratory-data-analysis-I_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\n## Summary statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngerrymander_24 |>\n  summarize(\n    mean = mean(trump_24),\n    sd = sd(trump_24),\n    min = min(trump_24),\n    q25 = quantile(trump_24, 0.25),\n    median = median(trump_24),\n    q75 = quantile(trump_24, 0.75),\n    max = max(trump_24),\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 7\n   mean    sd   min   q25 median   q75   max\n  <dbl> <dbl> <dbl> <dbl>  <dbl> <dbl> <dbl>\n1  49.2  15.2  10.6  37.9   50.3  61.0  83.0\n```\n\n\n:::\n:::\n\n\n## Distribution of votes for Trump in the 2024 election {.smaller}\n\n::: question\nDescribe the distribution of percent of vote received by Trump in 2024 Presidential Election from Congressional Districts.\n:::\n\n-   Shape: [The distribution of votes for Trump in the 2024 election from Congressional Districts is **unimodal and left-skewed**.]{.fragment}\n\n-   Center: [The percent of vote received by Trump in the 2024 Presidential Election from a **typical** Congressional Districts is 50.3%.]{.fragment}\n\n-   Spread: [In the **middle 50%** of Congressional Districts, 37.9% to 61% of voters voted for Trump in the 2024 Presidential Election.]{.fragment}\n\n-   Unusual observations: [-]{.fragment}\n\n# Bivariate analysis\n\n## Bivariate analysis\n\nAnalyzing the relationship between two variables:\n\n::: incremental\n-   Numerical + numerical: scatterplot\n\n-   Numerical + categorical: side-by-side box plots, violin plots, etc.\n\n-   Categorical + categorical: stacked bar plots\n\n-   Using an aesthetic (e.g., fill, color, shape, etc.) or facets to represent the second variable in any plot\n:::\n\n## Side-by-side box plots\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code  code-line-numbers=\"|2|3-6|8\"}\nggplot(\n  gerrymander_24,\n  aes(\n    x = trump_24,\n    y = gerry_24\n  )\n) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](05-exploratory-data-analysis-I_files/figure-html/unnamed-chunk-34-1.png){width=480}\n:::\n:::\n\n\n## Participate 📱💻 {.smaller}\n\n::: {.columns}\n\n::: {.column width=\"85%\"}\n\n::: wooclap\nWhat goes in the `[blank]` in the code below to do the following step for each level of `gerry_24`?\n\n::: {.columns}\n::: {.column width=\"60%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngerrymander_24 |>\n  # [blank]\n  summarize(\n    min = min(trump_24),\n    q25 = quantile(trump_24, 0.25),\n    median = median(trump_24),\n    q75 = quantile(trump_24, 0.75),\n    max = max(trump_24),\n  )\n```\n:::\n\n\n:::\n::: {.column width=\"40%\"}\n\n::: wooclap-choices\n- `filter(gerry_24)`\n- `group_by(gerry_24)`\n- `mutate(gerry_24)`\n- `select(gerry_24)`\n:::\n\n:::\n::: \n\n:::\n\n:::\n\n::: {.column width=\"15%\"}\n\n![](images/05/wooclap-qr.png){width=\"200\" fig-align=\"center\" fig-alt=\"QR code for Wooclap\"}\n\nGo to [wooclap.com](https://app.wooclap.com/KUCTINK) and use the code KUCTINK.\n\n:::\n\n::: \n\n## Grouped summary statistics {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngerrymander_24 |>\n  group_by(gerry_24) |>\n  summarize(\n    min = min(trump_24),\n    q25 = quantile(trump_24, 0.25),\n    median = median(trump_24),\n    q75 = quantile(trump_24, 0.75),\n    max = max(trump_24),\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  gerry_24   min   q25 median   q75   max\n  <chr>    <dbl> <dbl>  <dbl> <dbl> <dbl>\n1 A         10.8  36.7   47.0  57.7  81.3\n2 B         10.6  32.8   44.0  52.4  83.0\n3 C         39.3  59.7   65.5  70.7  77.0\n4 D         22.1  43.0   51.3  61.5  73.4\n5 F         13.5  45.9   57.7  62.2  78.4\n6 <NA>      32.6  37.8   43.6  61.2  72.3\n```\n\n\n:::\n:::\n\n\n## `NA` for gerrymandering?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|2|3\"}\ngerrymander_24 |>\n  filter(is.na(gerry_24)) |>\n  select(district, starts_with(\"state\"), starts_with(\"gerry\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 6\n   district state_abb state        gerry_22 gerry_24 gerry_26\n   <chr>    <chr>     <chr>        <chr>    <chr>    <chr>   \n 1 AK-00    AK        Alaska       <NA>     <NA>     <NA>    \n 2 DE-00    DE        Delaware     <NA>     <NA>     <NA>    \n 3 HI-01    HI        Hawaii       <NA>     <NA>     <NA>    \n 4 HI-02    HI        Hawaii       <NA>     <NA>     <NA>    \n 5 ND-00    ND        North Dakota <NA>     <NA>     <NA>    \n 6 RI-01    RI        Rhode Island <NA>     <NA>     <NA>    \n 7 RI-02    RI        Rhode Island <NA>     <NA>     <NA>    \n 8 SD-00    SD        South Dakota <NA>     <NA>     <NA>    \n 9 VT-00    VT        Vermont      <NA>     <NA>     <NA>    \n10 WY-00    WY        Wyoming      <NA>     <NA>     <NA>    \n```\n\n\n:::\n:::\n\n\n## Density plots\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|2|3|4\"}\ngerrymander_24 |>\n  filter(!is.na(gerry_24)) |>\n  ggplot(aes(x = trump_24, color = gerry_24)) +\n  geom_density()\n```\n\n::: {.cell-output-display}\n![](05-exploratory-data-analysis-I_files/figure-html/unnamed-chunk-38-1.png){width=672}\n:::\n:::\n\n\n## Filled density plots\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|3\"}\ngerrymander_24 |>\n  filter(!is.na(gerry_24)) |>\n  ggplot(aes(x = trump_24, color = gerry_24, fill = gerry_24)) +\n  geom_density()\n```\n\n::: {.cell-output-display}\n![](05-exploratory-data-analysis-I_files/figure-html/unnamed-chunk-39-1.png){width=672}\n:::\n:::\n\n\n## Better filled density plots\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|4\"}\ngerrymander_24 |>\n  filter(!is.na(gerry_24)) |>\n  ggplot(aes(x = trump_24, color = gerry_24, fill = gerry_24)) +\n  geom_density(alpha = 0.5)\n```\n\n::: {.cell-output-display}\n![](05-exploratory-data-analysis-I_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n:::\n\n\n## Better colors {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|5-6\"}\ngerrymander_24 |>\n  filter(!is.na(gerry_24)) |>\n  ggplot(aes(x = trump_24, color = gerry_24, fill = gerry_24)) +\n  geom_density(alpha = 0.5) +\n  scale_color_viridis_d() +\n  scale_fill_viridis_d()\n```\n\n::: {.cell-output-display}\n![](05-exploratory-data-analysis-I_files/figure-html/unnamed-chunk-41-1.png){width=672}\n:::\n:::\n\n\n## Violin plots {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"4\"}\ngerrymander_24 |>\n  filter(!is.na(gerry_24)) |>\n  ggplot(aes(x = trump_24, y = gerry_24, color = gerry_24)) +\n  geom_violin() +\n  scale_color_viridis_d()\n```\n\n::: {.cell-output-display}\n![](05-exploratory-data-analysis-I_files/figure-html/unnamed-chunk-42-1.png){width=672}\n:::\n:::\n\n\n## Multiple geoms {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|5\"}\ngerrymander_24 |>\n  filter(!is.na(gerry_24)) |>\n  ggplot(aes(x = trump_24, y = gerry_24, color = gerry_24)) +\n  geom_violin() +\n  geom_point() +\n  scale_color_viridis_d()\n```\n\n::: {.cell-output-display}\n![](05-exploratory-data-analysis-I_files/figure-html/unnamed-chunk-43-1.png){width=672}\n:::\n:::\n\n\n## Multiple geoms {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|5\"}\ngerrymander_24 |>\n  filter(!is.na(gerry_24)) |>\n  ggplot(aes(x = trump_24, y = gerry_24, color = gerry_24)) +\n  geom_violin() +\n  geom_jitter() +\n  scale_color_viridis_d()\n```\n\n::: {.cell-output-display}\n![](05-exploratory-data-analysis-I_files/figure-html/unnamed-chunk-44-1.png){width=672}\n:::\n:::\n\n\n## Remove legend {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|7\"}\ngerrymander_24 |>\n  filter(!is.na(gerry_24)) |>\n  ggplot(aes(x = trump_24, y = gerry_24, color = gerry_24)) +\n  geom_violin() +\n  geom_jitter() +\n  scale_color_viridis_d() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](05-exploratory-data-analysis-I_files/figure-html/unnamed-chunk-45-1.png){width=672}\n:::\n:::\n\n",
    "supporting": [
      "05-exploratory-data-analysis-I_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}